### ISSUE TITLE
Pushing to GCR errors with `"docker-credential-gcloud": executable file not found in $PATH`

### ISSUE THREAD

**Issue by glennslaven** [engineerd/wasm-to-oci#12]
```
$ gcloud version
Google Cloud SDK 304.0.0
bq 2.0.58
core 2020.07.31
gsutil 4.52
```

wasm-to-oci version 0.1.1

Running `wasm-to-oci push target/wasm32-wasi/debug/demo.wasm gcr.io/<registry_path>` returns
`Error: error getting credentials - err: exec: "docker-credential-gcloud": executable file not found in $PATH, out: ```

docker pushing to gcr.io works fine.

**Comment by radu-matei** [comment]
Hi, @glennslaven!
I am not familiar with how `docker-credential-gcloud` is working - `wasm-to-oci` reads the `~/.docker/config.json` file and uses the credentials there to push to the registry - in short, if you logged in to the registry, and the registry supports [OCI Artifacts](https://github.com/opencontainers/artifacts), it should work.

I suspect that for GCR repositories, the credentials are retrieved just-in-time by the `docker-credential-gcloud` utility - I think that if you login using the access token, as described in [the GCR authentication docs](https://cloud.google.com/container-registry/docs/advanced-authentication), this should work.

**Comment by jiayihu** [comment]
I can confirm it works fine logging in with Docker using the access token

**Comment by radu-matei** [comment]
Thanks a lot for the confirmation, @jiayihu!

Closing for now, but feel free to reopen if this is still an issue.
